services:
  db:
    image: postgres:15-alpine
    container_name: auth-starter-db
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-auth_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: auth-starter-backend
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@db:5432/${DB_NAME:-auth_db}
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET:-secret_access}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET:-secret_refresh}
      PORT: 3000
      FRONTEND_URL: http://localhost:5173
      NODE_ENV: development
      RESEND_API_KEY: ${RESEND_API_KEY}
      SMTP_HOST: ${SMTP_HOST:-mailhog}
      SMTP_PORT: ${SMTP_PORT:-1025}
      EMAIL_FROM: ${EMAIL_FROM:-onboarding@example.com}
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
    container_name: auth-starter-frontend
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:3000/api
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

  mailhog:
    image: mailhog/mailhog
    container_name: auth-starter-mailhog
    ports:
      - "1025:1025" # SMTP port
      - "8025:8025" # Web UI port

volumes:
  postgres_data:
